apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort  # Change to NodePort to access Grafana externally
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000  # You can specify a NodePort if needed
  selector:
    app: grafana
